export const validSigns = [
  "above", "accept", "accomplish", "acquire", "act", "action", "add", "addict",
  "address", "admit", "adopt", "adult", "after", "again", "against", "age",
  "all", "alone", "alright", "always", "amazing", "analyze", "and", "angry",
  "announce", "answer", "any", "anyone", "apart", "argue", "assign", "at",
  "attention", "attitude", "audience", "avoid", "away", "baby", "back",
  "barely", "basic", "basket", "bath", "battery", "bed", "behavior", "believe",
  "benefit", "best", "big", "bird", "birthday", "bite", "blind", "blood",
  "boat", "body", "boil", "bomb", "bone", "book", "bored", "borrow", "both",
  "bowl", "boy", "brainstorm", "brainwash", "breathe", "brother", "budget",
  "burn", "busy", "but", "buy", "bye", "call", "calm", "cannot", "cards",
  "careful", "category", "caught", "challenge", "chance", "chat", "check",
  "child", "close", "clothes", "email", "embarrass", "emotion", "energy",
  "engagement", "engineer", "english", "enjoy", "enter", "equal", "escape",
  "event", "examples", "excited", "exercise", "experience", "expert", "face",
  "fail", "fall", "family", "famous", "far", "fault", "faulty", "fedup", "feel",
  "few", "fight", "film", "finally", "finance", "find", "finish", "fire",
  "first", "fix", "flag", "float", "focus", "fool", "for", "forgetful", "form",
  "freakout", "freedom", "friend", "frustate", "fun", "future", "game", "get",
  "gift", "go", "greet", "guess", "guilty", "habbit", "happen", "happy", "hate",
  "have", "health", "hear", "help", "here", "high", "his", "holiday", "honest",
  "hope", "house", "humbel", "hurry", "hurt", "husband", "idea", "ignore",
  "improve", "in", "independent", "innocent", "inspire", "instead",
  "intelligent", "interept", "interest", "interview", "invite", "jealous",
  "judge", "jump", "keep", "kid", "kill", "know", "laugh", "lazy", "learn",
  "leave", "less", "list", "lonely", "long", "lost", "loud", "love", "loyal",
  "luck", "lunch", "mad", "make", "man", "manage", "many", "me", "meet",
  "member", "not", "off", "ok", "on", "once", "one", "or", "out", "outside",
  "over", "overwhelmed", "own", "pain", "party", "past", "peace", "positive",
  "reach", "react", "read", "ready", "really", "reason", "reduce", "refuse",
  "relationship", "release", "religion", "remember", "remind", "remove",
  "resent", "responsibility", "rest", "result", "revenge", "risk", "road",
  "roof", "room", "rope", "sad", "salad", "same", "scarcely", "scared",
  "sneeze", "snow", "son", "sorry", "soup", "sour", "space", "special",
  "specific", "spend", "sport", "spread", "spring", "square", "stadium",
  "stamp", "stand", "star", "state", "stay", "stop", "story", "straight",
  "strange", "straw", "stress", "strict", "string", "strong", "struggle",
  "stuck", "student", "study", "stupid", "suit", "sun", "support", "sure",
  "therapy", "trouble", "ugly", "unaware", "uncertain", "upset", "value",
  "want", "wish", "wonder", "worry", "you"
];
